export const bankOptions = [
  { label: 'Agribank', value: 0 },
  { label: 'VietinBank', value: 1 },
  { label: 'Vietcombank', value: 2 },
  { label: 'BIDV', value: 3 },
  { label: 'Techcombank', value: 4 },
  { label: 'MB', value: 5 },
  { label: 'VPBank', value: 6 },
  { label: 'ACB', value: 7 },
  { label: 'Sacombank', value: 8 },
  { label: 'SHB', value: 9 },
  { label: 'MSB', value: 10 },
  { label: 'HDBank', value: 11 },
  { label: 'TPBank', value: 12 },
  { label: 'VIB', value: 13 },
  { label: 'DongA Bank', value: 14 },
  { label: 'Nam A Bank', value: 15 },
  { label: 'LienVietPostBank', value: 16 },
  { label: 'SCB', value: 17 },
  { label: 'Eximbank', value: 18 },
  { label: 'Bac A Bank', value: 19 },
  { label: 'Viet Capital Bank', value: 20 },
  { label: 'VietABank', value: 21 },
  { label: 'ABBANK', value: 22 },
  { label: 'KienlongBank', value: 23 },
  { label: 'SeABank', value: 24 },
  { label: 'Saigonbank', value: 25 },
  { label: 'GPBank', value: 26 },
  { label: 'PVcomBank', value: 27 },
  { label: 'OceanBank', value: 28 },
  { label: 'PG Bank', value: 29 },
  { label: 'HSBC', value: 30 },
  { label: 'Standard Chartered', value: 31 },
  { label: 'ANZ', value: 32 },
  { label: 'Shinhan Bank', value: 33 },
  { label: 'Woori Bank', value: 34 },
  { label: 'Hong Leong Bank', value: 35 },
  { label: 'UOB', value: 36 },
  { label: 'Public Bank', value: 37 },
  { label: 'CIMB', value: 38 },
  { label: 'Hana Bank', value: 39 },
];
